### PR TITLE
minimal fixes for python3 syntax

### PR DESCRIPTION
**Pull request by fchapoton**
This is fixing (as suggested by the ruff linter) the syntax for compatibility with python3.

This needs to be tested before merging.

### CODE REVIEW

**Comment by fchapoton** [comment]
I did not manage to fix the compilation : it breaks by not finding Python.h already

**Comment by fchapoton** [comment]
Now the test does not pass.  There seem to be a duplication of every graph somewhere.

**Comment by fchapoton** [comment]
Now the first test passes, but still not the second one.

**Comment by fchapoton** [comment]
What is the expected result of 

`./feyngen 2 -j2 -p`

?

**Comment by michibo** [comment]
The expected output is 

phi4_j2_h2 :=
+G[[1,0],[1,0],[1,1],[2,0],[3,0]]/4
+G[[1,0],[1,0],[1,0],[2,0],[3,1]]/6
;


Thanks again for your contributions!

**Comment by fchapoton** [comment]
now failing at a later step

**Comment by fchapoton** [comment]
Now the two tests in README do pass.

**Comment by fchapoton** [comment]
There remains to fix some `def flip` twice.

It remains also to make a better Makefile (not my expertise, I had to hardcode the version of Python).

**Comment by fchapoton** [comment]
The flips are fixed now. Please test and report failures.

**Comment by michibo** [comment]
I ran a couple of more tests and everything worked after minimal additional tweaks. It is merged into the main branch now. Thank you!

**Comment by fchapoton** [comment]
ok, good. Please tell me if I can go on and do some further cautious code-cleaning.

**Comment by michibo** [comment]
You are very welcome to do additional code cleaning! Thanks

**Pull request merged**
